/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SearchTodoStatus = {
    All: 'all',
    Done: 'done',
    Pending: 'pending'
} as const;
export type SearchTodoStatus = typeof SearchTodoStatus[keyof typeof SearchTodoStatus];


export function SearchTodoStatusFromJSON(json: any): SearchTodoStatus {
    return SearchTodoStatusFromJSONTyped(json, false);
}

export function SearchTodoStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchTodoStatus {
    return json as SearchTodoStatus;
}

export function SearchTodoStatusToJSON(value?: SearchTodoStatus | null): any {
    return value as any;
}

