/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TodoCreate
 */
export interface TodoCreate {
    /**
     * 
     * @type {string}
     * @memberof TodoCreate
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof TodoCreate
     */
    description: string;
    /**
     * 
     * @type {boolean}
     * @memberof TodoCreate
     */
    is_done: boolean;
}

/**
 * Check if a given object implements the TodoCreate interface.
 */
export function instanceOfTodoCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "is_done" in value;

    return isInstance;
}

export function TodoCreateFromJSON(json: any): TodoCreate {
    return TodoCreateFromJSONTyped(json, false);
}

export function TodoCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TodoCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'],
        'is_done': json['is_done'],
    };
}

export function TodoCreateToJSON(value?: TodoCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'description': value.description,
        'is_done': value.is_done,
    };
}

